---

- name: Test the ansible-django-api role
  hosts: all
  remote_user: root
  become: true
  roles:
    - role: api-ansible-role
  environment:
    CC: gcc-7
    CFLAGS: -I/opt/deps/include
    LDFLAGS: -L/opt/deps/lib
    LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/opt/deps/lib
