---
# Deploy the application

- name: Checkout the latest source code
  git:
    repo={{ app_repository }}
    dest={{ app_directory }}
    version={{ app_version }}
    accept_hostkey=true
    force=yes

- name: Ensure .env
  template:
    src: "env.j2"
    dest: "{{ app_directory }}/.env"

- name: Install gunicorn
  pip:
    virtualenv_python: "3.9"
    virtualenv: "{{ app_env }}"
    chdir: "{{ app_directory }}"
    name: gunicorn
    state: absent

- name: Install daphne
  pip:
    virtualenv_python: "3.9"
    virtualenv: "{{ app_env }}"
    chdir: "{{ app_directory }}"
    name: daphne
    state: present

- name: Install application dependencies
  pip:
    virtualenv_python: "3.9"
    virtualenv: "{{ app_env }}"
    chdir: "{{ app_directory }}"
    requirements: "requirements.txt"
    state: present

- name: Run migrations
  shell:
    cmd: |
      source {{ app_env }}/bin/activate
      {{ app_env }}/bin/python3.9 manage.py migrate
    chdir: "{{ app_directory }}"

- name: restart nginx
  systemd: name=nginx state=restarted enabled=yes

- name: Ensure application is restartet
  service: name=supervisor state=restarted

- name: enable rqworker
  service:
    name: rqworker
    enabled: yes

- name: restart rqworker
  service:
    name: rqworker
    state: restarted
